// Map of area codes to states
 let areaCodes = {
     "201": "New Jersey - OHH",
     "202": "District of Columbia",
 "651": "St. Paul, Minnesota - STLukes",
 "320": "Hutchinson, Minnesota - STLukes",
 "763": "Coon Rapids, Minnesota - STLukes",
 "507": "Owatonna, Minnesota - STLukes",
 "612": "Minneapolis, Minnesota - STLukes",
 "844": "Mountain Grove, Missouri - Aerocare",
 "660": "Kirksville, Missouri - Aerocare",
 "816": "Kansas City, Missouri - Aerocare",
 "573": "Columbia, Missouri - Aerocare",
 "417": "Lebanon, Missouri - Aerocare",
 "573": "Jefferson City, Missouri - Aerocare",
 "660": "Marshall, Missouri - Aerocare",
 "417": "Springfield, Missouri - Aerocare",
 "314": "St. Louis, Missouri - Aerocare",
 "606": "Ashland, Kentucky - STLukes",
 "589": "Lexington, Kentucky - STLukes",
 "502": "Lousville, Kentucky - STLukes",
 "270": "Bowling Green, Kentucky - STLukes",
 "606": "Somerset, Kentucky - STLukes",
 "866": "Murray, Kentucky - STLukes",
 "270": "Paducah, Kentucky - STLukes",
 "859": "Mount Sterling, Kentucky - STLukes",
 "828": "Brevard, North Carolina - STLukes",
 "336": "Greensboro, North Carolina - STLukes",
 "910": "Dunn, North Carolina - STLukes",
 "252": "New Bern, North Carolina - STLukes",
 "919": "Cary, North Carolina - STLukes",
 "336": "Lexington, North Carolina - STLukes",
 "252": "Wilson, North Carolina - STLukes",
 "704": "Charlotte, North Carolina - STLukes",
 "814": "Erie, Pennsylvania - STLukes",
 "800": "Danville, Pennsylvania - STLukes",
 "717": "Harrisburg, Pennsylvania - STLukes",
 "912": "Statesboro, Georgia - Aerocare",
 "678": "Stockbridge, Georgia - Aerocare",
 "770": "Marietta, Georgia - Aerocare",
 "706": "Augusta, Georgia - Aerocare",
 "470": "Loganville, Georgia - Aerocare",
 "229": "Albany, Georgia - Aerocare",
 "478": "Macon, Georgia - Aerocare",
 "813": "Tampa, Florida - Aerocare",
 "305": "Pembroke Pines, Florida - Aerocare",
 "727": "Clearwater, Florida - Aerocare",
 "941": "Bradenton, Florida - Aerocare",
 "863": "Sebring, Florida - Aerocare",
 "772": "Port St. Lucie, Florida - Aerocare",
 "561": "Boynton Beach, Florida - Aerocare",
 "239": "Fort Myers, Florida - Aerocare",
 "904": "Jacksonville, Florida - Aerocare",
 "321": "Melbourne, Florida - Aerocare",
 "407": "Kissimmee, Florida - Aerocare",
 "850": "Pensacola, Florida - Aerocare",
 "352": "Ocala, Florida - Aerocare",
 "239": "Fort Myers, Florida - Aerocare",
 "813": "Lakeland, Florida - Aerocare",
 "386": "Daytona Beach, Florida - Aerocare",
 "718": "Brooklyn, New York - OHH",
 "516": "Roslyn Heights, New York - OHH",
 "877": "Sayreville, New Jersey - OHH",
 "800": "Sayreville, New Jersey - OHH",
 "914": "White Plains, New York - OHH",
 "732": "Lakewood, New York - OHH",
 "631": "Ronkonkoma, New York - OHH",
 "860": "Fairfield, Connecticut - OHH",
 "215": "Huntingdon Valley, Penssylvenia - OHH",
 "610": "New york or Pennsylvania - OHH/STLukes",
 "570": "Stroudsburg, Pennsylvania - OHH",
 "845": "Highland, New York - OHH",
 "856": "Cinnaminson, New Jersey - OHH",
 "302": "New Castle, Delaware- STLukes",
 "717": "East Petersburg, Pennsylvania - STLukes",
 "410": "Havre de Grace, Middle River - STLukes",
 "240": "Oakland, Middle River - STLukes",
 "301": "Germandtown, Middle River - STLukes",
 "203": "Waterbury, Connecticut - OHH",
 "757": "Newport News, Virginia - STLukes",
 "800": "Lorton, Virginia - STLukes",
 "434": "South Hill, Virginia - STLukes",
 "276": "Lebanon, Virginia - STLukes",
 "540": "Waynesboro, Virginia - STLukes",
 "804": "Richmond, Virginia - STLukes",
 "301": "Fairfax, Virginia - STLukes",
 "740": "Gallipolis, Ohio - Aerocare",
 "330": "Akron, Ohio - Aerocare",
 "513": "Blue Ash, Ohio - Aerocare",
 "330": "Akron, Ohio - Aerocare",
 "614": "Columbus, Ohio - Aerocare",
 "888": "Northfield, Ohio - Aerocare",
 "937": "Kettering, Ohio - Aerocare",
 "501": "Searcy, Arkansas - Aerocare",
 "479": "Springdale, Arkansas - Aerocare",
 "870": "Jonesboro, Arkansas - Aerocare",
 "501": "Benton, Arkansas - Aerocare",
 "870": "Monticello, Arkansas - Aerocare",
 "479": "Bentonville, Arkansas - Aerocare",
 "866": "Russelville, Arkansas - Aerocare",
 "903": "Sherman, Texas - STLukes",
 "254": "Temple, Texas - STLukes",
 "940": "Wichita Falls, Texas - STLukes",
 "817": "Weatherford, Texas - STLukes",
 "480": "Phoenix, Arizona - Aerocare",
 "623": "Phoenix, Arizona - Aerocare",
 "931": "Tullahoma, Tennessee - Aerocare",
 "615": "Murfreesboro, Tennessee - Aerocare",
 "505": "Allentown, Pennsylvania - STLukes",
 "415": "San Francisco, California - STLukes",
 "469": "Arlington, Texas - STLukes",
 "214": "Arlington, Texas - STLukes",
 "405": "Oklahoma City, Oklahoma - Aerocare",
 "779": "Cibolo, Texas - STLukes",
 "443": "Elkton, Middle Rider - STLukes",
 "210": "San Antonio, Texas - STLukes",
 "702": "Las Vegas Nevada - STLukes",
 "650": "Tracy California - STLukes",
 "510": "Fairfield, California - STLukes",
 "209": "Linden, California - STLukes",
 "559": "Fresno, California - STLukes",
 "970": "Collins, Colorado - Aerocare",
 "707": "Suisun City, California - STLukes",
 "865": " Knoxville, Tennessee - Aerocare",
 "815": "Union, Illinois - STLukes",
 "708": "Chicago, Illinois - STLukes",
 "224": "Lakemore, Illinois - STLukes",
 "773": "Niles, Illinois - STLukes",
 "312": "Niles, Illinois - STLukes",
 "208": "Blackfoot, Idaho - STLukes",
 "602": "Maricopa, Arizona - STLukes",
 "402": "Albion, Nebraska - Aerocare",
 "806": "Amarillo, Texas - STLukes",
 "262": "Waukesha, New Berlin - Aerocare",
 "713": "League City, Texas - STLukes",
 "505": "New Mexico or Pennsylvania - STLukes",
 "830": "Luling, Texas - STLukes",
 "973": "South Orange, New Jersey - OHH",
 "843": "North Charleston, South Carolina - Aerocare",
 "681": "Charleston, West Virginia - Aerocare",
 "267": "Commonwealth, Pennsylvania - STLukes",
 "847": "Wilmette, Illinois - STLukes",
 "719": "Colorado Springs, Colorado - Aerocare",
 "607": "CODE",
 "972": "Midlothian, Texas - STLukes",
 "609": "Pleasantville, New Jersey - OHH",
 "803": "Pleasantville, New Jersey - OHH",
 "303": "Denver, Colorado - Aerocare",
 "401": "Rhode Island - OHH",
 "802": "Vermont - OHH",
 "475": "Connecticut - OHH",
 "860": "Connecticut - OHH",
 "959": "Connecticut - OHH",
 "212": "New York -  OHH",
 "917": "New York -  OHH",
 "646": "New York -  OHH",
 "585": "New York -  OHH",
 "607": "New York -  OHH",
 "347": "New York -  OHH",
 "716": "New York -  OHH",
 "458": "Oregon - STLukes",
 "503": "Oregon - STLukes",
 "541": "Oregon - STLukes",
 "971": "Oregon - STLukes",
 "218": "Minessota - STLukes",
 "952": "Minessota - STLukes",
"812": "Indiana - STLukes",
 "930": "Indiana - STLukes",
 "463": "Indiana - STLukes",
 "317": "Indiana - STLukes",
 "575": "New Mexico - STLukes",
 "213": "California - STLukes",
 "916": "California - STLukes",
 "530": "California - STLukes",
 "818": "California - STLukes",
 "619": "California - STLukes",
 "725": "Nevada - STLukes",
 "775": "Nevada - STLukes",
 "217": "Illinois - STLukes",
 "309": "Illinois - STLukes",
 "331": "Illinois - STLukes",
 "618": "Illinois - STLukes",
 "630": "Illinois - STLukes",
 "872": "Illinois - STLukes",
 "667": "Maryland - STLukes",
 "703": "Virginia - STLukes",
 "281": "Texas - STLukes",
 "325": "Texas - STLukes",
 "346": "Texas - STLukes",
 "361": "Texas - STLukes",
 "409": "Texas - STLukes",
 "430": "Texas - STLukes",
 "432": "Texas - STLukes",
 "512": "Texas - STLukes",
 "682": "Texas - STLukes",
 "737": "Texas - STLukes",
 "832": "Texas - STLukes",
 "915": "Texas - STLukes",
 "936": "Texas - STLukes",
 "956": "Texas - STLukes",
 "979": "Texas - STLukes",
 "983": "Colorado -Aerocare",
 "423": "Tennessee - Aerocare",
 "731": "Tennessee - Aerocare",
 "901": "Tennessee - Aerocare",
 "571": "Tennessee - Aerocare",
 "327": "Arizona - Aerocare",
 "404": "Georgia - Aerocare",
 "762": "Georgia - Aerocare",
 "364": "Kentucky - Aerocare",
 "414": "Wisconsin - Aerocare",
 "608": "Wisconsin - Aerocare",
 "715": "Wisconsin - Aerocare",
 "534": "Wisconsin - Aerocare",
 "228": "Mississippi - Aerocare",
 "601": "Mississippi - Aerocare",
 "662": "Mississippi - Aerocare",
 "769": "Mississippi - Aerocare",
 "216": "Ohio - Aerocare",
 "419": "Ohio - Aerocare",
 "440": "Ohio - Aerocare",
 "839": "South Carolina  - Aerocare",
 "854": "South Carolina  - Aerocare",
 "864": "South Carolina  - Aerocare",
 "821": "South Carolina  - Aerocare",
 "319": "Iowa - Aerocare",
 "515": "Iowa - Aerocare",
 "563": "Iowa - Aerocare",
 "641": "Iowa - Aerocare",
 "712": "Iowa - Aerocare",
 "754": "Florida - Aerocare",
 "786": "Florida - Aerocare",
 "954": "Florida - Aerocare",
 "205": "Alabama - Aerocare",
 "251": "Alabama - Aerocare",
 "256": "Alabama - Aerocare",
 "334": "Alabama - Aerocare",
 "938": "Alabama - Aerocare",
 "323": "Lost Angeles - Aerocare",
 "539": "Oklahoma - Aerocare",
 "580": "Oklahoma - Aerocare",
 "636": "Missouri - Aerocare",
 "231": "Michigan - Aerocare",
 "248": "Michigan - Aerocare",
 "269": "Michigan - Aerocare",
 "313": "Michigan - Aerocare",
 "517": "Michigan - Aerocare",
 "586": "Michigan - Aerocare",
 "616": "Michigan - Aerocare",
 "734": "Michigan - Aerocare",
 "810": "Michigan - Aerocare",
 "906": "Michigan - Aerocare",
 "947": "Michigan - Aerocare",
 "989": "Michigan - Aerocare",
 "CODE": "CODE",
 "CODE": "CODE",
 "CODE": "CODE",
    // Add more area codes here
 };
document.getElementById('phone-form').addEventListener('submit', function(event) {
     event.preventDefault();
     let phone = document.getElementById('phone').value;
     let state = areaCodes[phone];
     if (state) {
         document.getElementById('result').textContent = 'The state is: ' + state;
     } else {
         document.getElementById('result').textContent = 'Area code not found.';
     }
 });
  
